### ISSUE TITLE
src/Plugin.phpについて

### ISSUE THREAD

**Issue by binbin4649** [baserproject/BcBake#1]
bin/cake bake bc_plugin Hoge
とした場合、src/HogePlugin.phpが作られますが、画面からインストールしようとすると、
「プラグインに Plugin クラスが存在しません。src ディレクトリ配下に作成してください。」
と、たぶんsrc/Plugin.phpがないと怒られます。
実際は、src/HogePlugin.phpとsrc/Plugin.phpはどちらが正解なのでしょうか？

**Comment by ryuring** [comment]
@binbin4649 CakePHPのバージョンは何になってます？
CakePHP5系からHogePluginとなるようです。

**Comment by binbin4649** [comment]
@ryuring 
dev-5をcloneしてるので、cakephp4.4です。
cakephp5で変わるんですね、、、
ちなみに、やり直してみたらHogePluginでも行けたみたいです、
